const productData = {
    products: [
        {
            id: 1,
            thumbnail: "https://rukminim2.flixcart.com/image/416/416/k6fd47k0pkrrdj/printer/r/g/r/canon-pixma-mg3070s-original-imafbu3ypdzxq3wb.jpeg?q=70&crop=false",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"1000",
        },
        {
            id: 2,
            thumbnail: "https://rdp.in/web/image/799165/desk-pc-header.png",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"2000",
        },
        {
            id: 3,
            thumbnail: "https://m.media-amazon.com/images/I/41JCNHP4FeL._AC_UF1000,1000_QL80_.jpg",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"3000",
        },
        {
            id: 4,
            thumbnail: "https://png.pngtree.com/element_our/20190528/ourmid/pngtree-computer-accessories-stereo-red-headphones-image_1160091.jpg",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"2500",
        },
        {
            id: 5,
            thumbnail: "https://t3.ftcdn.net/jpg/01/82/40/80/360_F_182408083_2tFZnlAKOwGPWgjbU1RcUtYJj5WJFi57.jpg",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"1500",
        },
        {
            id: 6,
            thumbnail: "https://m.media-amazon.com/images/I/51XHcbJ4QWL._AC_UF1000,1000_QL80_.jpg",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"1300",
        },
        {
            id: 7,
            thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWzcHs_kcJgMQwx3CctDumr4Fwkac7Woj3KSn_REd25Q&s",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"3500",
        },
        {
            id: 8,
            thumbnail: "https://media.istockphoto.com/id/671061906/photo/computer-mouse.jpg?s=612x612&w=0&k=20&c=MEHIcn7TxnIsvby8eJj7uizG3fUoe8GJ8XDl1Lr1vmk=",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"7500",
        },
        {
            id: 9,
            thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8cDS6bo0exeEXzKIIhkngH0AiK5fV3vKO-vM0jqaBDg&s",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"8900",
        },
        {
            id: 10,
            thumbnail: "https://m.media-amazon.com/images/I/61852LMSpPL.jpg",
            price: "₹3299",
            title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
            rating: "3.7",
            caption: "Canon MG2570S Multi-function Color",
            price:"500",
        },
        // {
        //     id: 11,
        //     thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl2imjgZ6kMryNoJu6imKrYCI29R5MMEZB8Im7tS2f3g&s",
        //     price: "₹3299",
        //     title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
        //     rating: "3.7",
        //     caption: "Canon MG2570S Multi-function Color",
        //     price:"3000",
        // },
        // {
        //     id: 12,
        //     thumbnail: "https://www.shutterstock.com/image-photo/angle-shot-all-one-monoblock-260nw-234537736.jpg",
        //     price: "₹3299",
        //     title: "Canon MG2570S Multi-function Color Inkjet Printer  (Ink Cartridge)",
        //     rating: "3.7",
        //     caption: "Canon MG2570S Multi-function Color",
        //     price:"3000",
        // },
    ]
};

export default productData;
